---
output:
  pdf_document: default
  html_document: default
---
# Assignment: American Community Survey Exercise
# Name: Quintero Vasquez, Johnatan
# Date: 2023-06-25

## Load the ggplot2 package
library(ggplot2)
theme_set(theme_minimal())

## Set the working directory to the root of your DSC 520 directory
setwd("C:/Users/21428899/OneDrive - Bellevue University/Documents/GitHub/dsc520")

## Load the `data/acs-14-1yr-s0201.csv` to
survey_df <- read.csv("data/acs-14-1yr-s0201.csv")

# 1. What are the elements in your data (including the categories and data types)?

# 2.	Please provide the output from the following functions: str(); nrow(); ncol()
str(survey_df)
nrow(survey_df)
ncol(survey_df)

# 3.	Create a Histogram of the HSDegree variable using the ggplot2 package.
##  1.	Set a bin size for the Histogram.
##  2.	Include a Title and appropriate X/Y axis labels on your Histogram Plot.
ggplot(survey_df, aes(x = HSDegree)) + geom_histogram(bins = 10) +
  ggtitle("High School Degree") +
  xlab("HS Degree") +
  ylab("GPA")
  
#4.	Answer the following questions based on the Histogram produced:
##  1.	Based on what you see in this histogram, is the data distribution unimodal?
##  2.	Is it approximately symmetrical?
##  3.	Is it approximately bell-shaped?
##  4.	Is it approximately normal?
##  5.	If not normal, is the distribution skewed? If so, in which direction?
##  6.	Include a normal curve to the Histogram that you plotted.
##  7.	Explain whether a normal distribution can accurately be used as a model for this data.

#5.	Create a Probability Plot of the HSDegree variable.

#6.	Answer the following questions based on the Probability Plot:
#  1.	Based on what you see in this probability plot, is the distribution approximately normal? Explain how you know.
#  2.	If not normal, is the distribution skewed? If so, in which direction? Explain how you know.

#7.	Now that you have looked at this data visually for normality, you will now quantify normality with numbers using the stat.desc() function. Include a screen capture of the results produced.

#8.	In several sentences provide an explanation of the result produced for skew, kurtosis, and z-scores. In addition, explain how a change in the sample size may change your explanation?
  
  


